import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { redact, redactWithLinks, defangDomain } from "@/lib/redact";
import { SOURCES, BELIEFS } from "@/lib/constants";
const domain = z.string().max(255).nullable().optional();
const message = z.object({ messageText: z.string().min(5).max(8000), messageSource: z.enum(SOURCES), initialUserBelief: z.enum(BELIEFS), shortContext: z.string().max(280).optional(), inputMethod: z.enum(["eml_upload", "text_paste"]).default("text_paste"), sanitizedSubject: z.string().max(1000).optional(), sanitizedBody: z.string().max(8000).optional(), fromDomain: domain, replyToDomain: domain, returnPathDomain: domain, fromReplyToMismatch: z.boolean().nullable().optional(), linkFeatures: z.array(z.unknown()).max(50).optional(), authSummary: z.object({ spf: z.string(), dkim: z.string(), dmarc: z.string() }).optional(), hasAttachments: z.boolean().optional(), attachmentExtensions: z.array(z.string().max(20)).max(30).optional(), attachmentsStripped: z.boolean().optional(), emlParsedClientSide: z.boolean().optional() });
const input = z.object({ teracSubmissionId: z.string().min(1).max(200), wave: z.literal("collect").default("collect"), messages: z.array(message).length(2) });
const safeDomain = (value?: string | null) => value ? defangDomain(value.replaceAll("[.]", ".")) : null;
export async function POST(request: Request) { try { const data = input.parse(await request.json()); const beliefs = data.messages.map(item => item.initialUserBelief); if (!beliefs.includes("suspicious") || !beliefs.includes("legitimate")) return NextResponse.json({ error: "Please provide one suspicious and one normal or legitimate message." }, { status: 400 }); const participant = await prisma.teracParticipant.upsert({ where: { teracSubmissionId: data.teracSubmissionId }, update: { wave: data.wave }, create: { teracSubmissionId: data.teracSubmissionId, wave: data.wave } }); const already = await prisma.collectedMessage.count({ where: { submittedByParticipantId: participant.id } }); if (already >= 2) return NextResponse.json({ error: "Messages were already submitted for this participant." }, { status: 409 }); await prisma.$transaction(data.messages.map(item => { const body = redact(item.sanitizedBody ?? item.messageText); const subject = item.sanitizedSubject ? redact(item.sanitizedSubject) : null; const links = item.linkFeatures ?? redactWithLinks(item.messageText).links; const combined = [subject ? `Subject: ${subject}` : "", item.fromDomain ? `From domain: ${safeDomain(item.fromDomain)}` : "", item.replyToDomain ? `Reply-to domain: ${safeDomain(item.replyToDomain)}` : "", `Body: ${body}`].filter(Boolean).join("\n"); return prisma.collectedMessage.create({ data: { submittedByParticipantId: participant.id, sanitizedText: combined, inputMethod: item.inputMethod, sanitizedSubject: subject, sanitizedBody: body, source: item.inputMethod === "eml_upload" ? "email" : item.messageSource, initialUserBelief: item.initialUserBelief, shortContext: item.shortContext ? redact(item.shortContext) : null, fromDomain: safeDomain(item.fromDomain), replyToDomain: safeDomain(item.replyToDomain), returnPathDomain: safeDomain(item.returnPathDomain), fromReplyToMismatch: item.fromReplyToMismatch ?? null, linkFeatures: JSON.stringify(links), authSummary: item.authSummary ? JSON.stringify(item.authSummary) : null, hasAttachments: item.hasAttachments ?? false, attachmentExtensions: item.attachmentExtensions ? JSON.stringify(item.attachmentExtensions) : null, attachmentsStripped: item.attachmentsStripped ?? true, emlParsedClientSide: item.emlParsedClientSide ?? false } }); })); await prisma.teracParticipant.update({ where: { id: participant.id }, data: { status: "collection_completed", collectionCompletedAt: new Date(), completedAt: new Date() } }); return NextResponse.json({ ok: true }); } catch (error) { return NextResponse.json({ error: error instanceof z.ZodError ? error.issues[0]?.message : "Invalid request." }, { status: 400 }); } }
