import { cleanSanitizedText } from "@/lib/text-cleanup";
export type LinkFeature = { link_present: boolean; defanged_domain: string; tld: string; subdomain_count: number; contains_brand_term: boolean; possible_brand_term: string | null; brand_domain_mismatch: boolean; uses_url_shortener: boolean; has_ip_address: boolean; suspicious_keywords: string[]; path_removed: boolean; query_removed: boolean };
const brands = ["usps", "fedex", "ups", "amazon", "paypal", "venmo", "zelle", "chase", "linkedin", "instagram", "facebook", "google", "microsoft", "apple", "netflix"];
const shorteners = ["bit.ly", "tinyurl.com", "t.co", "goo.gl", "shorturl.at", "rb.gy"];
export function defangDomain(value: string) { return value.trim().toLowerCase().replace(/^www\./, "www.").replaceAll(".", "[.]"); }
export function domainFromAddress(value?: string | null) { const match = value?.match(/@([A-Z0-9.-]+\.[A-Z]{2,})/i); return match ? defangDomain(match[1]) : null; }
function featureFor(raw: string): LinkFeature { let url: URL | null = null; try { url = new URL(raw.startsWith("www.") ? `https://${raw}` : raw); } catch {} const host = url?.hostname.toLowerCase() ?? ""; const plainDomain = host.replace(/^www\./, ""); const words = `${host}${url?.pathname ?? ""}`.toLowerCase(); const brand = brands.find(item => words.includes(item)) ?? null; const suspicious = ["pay", "verify", "login", "secure", "delivery", "refund", "gift", "crypto"].filter(word => words.includes(word)); return { link_present: true, defanged_domain: defangDomain(plainDomain), tld: plainDomain.split(".").at(-1) ?? "", subdomain_count: Math.max(0, plainDomain.split(".").length - 2), contains_brand_term: Boolean(brand), possible_brand_term: brand, brand_domain_mismatch: Boolean(brand && !plainDomain.includes(brand)), uses_url_shortener: shorteners.includes(plainDomain), has_ip_address: /^\d{1,3}(\.\d{1,3}){3}$/.test(plainDomain), suspicious_keywords: suspicious, path_removed: Boolean(url?.pathname && url.pathname !== "/"), query_removed: Boolean(url?.search) };
}
export function redactWithLinks(text: string) { const links: LinkFeature[] = []; const sanitized = text.replace(/https?:\/\/[^\s<]+|www\.[^\s<]+/gi, raw => { const feature = featureFor(raw.replace(/[).,;!?]+$/, "")); links.push(feature); return `[LINK: hxxps://${feature.defanged_domain}/[PATH]]`; }).replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, "[EMAIL]").replace(/(?:\+?\d[\d().\-\s]{7,}\d)/g, "[PHONE]").replace(/\b\d{4,}\b/g, "[CODE]").replace(/\b\d{9,}\b/g, "[NUMBER]").replace(/\b\d{1,5}\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,3}\s+(?:Street|St\.?|Avenue|Ave\.?|Road|Rd\.?|Boulevard|Blvd\.?|Drive|Dr\.?|Lane|Ln\.?|Court|Ct\.?)\b/gi, "[ADDRESS]").replace(/\s{3,}/g, " ").trim(); return { sanitized: cleanSanitizedText(sanitized), links }; }
/** Applied in browser and again on server. Raw text is never persisted. */
export function redact(text: string) { return redactWithLinks(text).sanitized; }
